/* BILLING ONE v0.2.4 - PRECHECK - SOLO LECTURA / DBEAVER */

SELECT 'TABLAS_EXECUTION_EXISTENTES' CONTROL, COUNT(*) CANTIDAD
FROM USER_TABLES
WHERE TABLE_NAME IN ('RM_CFACT_EXECUTION_POLICY','RM_CFACT_EXECUTION_QUEUE');

SELECT 'FUENTES_EXISTENTES' CONTROL, COUNT(*) CANTIDAD
FROM RM_CFACT_DATA_SOURCE;

SELECT 'SCOPES_FUENTE_ACTIVOS' CONTROL, COUNT(*) CANTIDAD
FROM RM_CFACT_SOURCE_SCOPE
WHERE ACTIVE='Y';

SELECT 'ORIGEN_SGA' CONTROL, COUNT(*) CANTIDAD
FROM RM_CFACT_ORIGIN WHERE UPPER(ORIGIN_CODE)='SGA';

SELECT 'ORIGEN_DHT' CONTROL, COUNT(*) CANTIDAD
FROM RM_CFACT_ORIGIN WHERE UPPER(ORIGIN_CODE)='DHT';

SELECT 'SISGAV2_PROTEGIDA' CONTROL,
       CASE WHEN COUNT(*)=1 THEN 'EXISTE - FUERA DEL PARCHE'
            ELSE 'NO EXISTE - SIN ACCION' END ESTADO
FROM USER_TABLES WHERE TABLE_NAME='SISGAV2';

/* Para aplicar 10_APPLY.sql, TABLAS_EXECUTION_EXISTENTES debe ser 0. */
