/* BILLING ONE v0.2.4 - VALIDACION POST PARCHE - SOLO LECTURA */

SELECT 'TABLAS_EXECUTION' CONTROL, COUNT(*) REAL, 2 ESPERADO,
       CASE WHEN COUNT(*)=2 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN ('RM_CFACT_EXECUTION_POLICY','RM_CFACT_EXECUTION_QUEUE');

SELECT 'FUENTES_SIN_POLITICA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_EXECUTION_POLICY P ON P.DATA_SOURCE_ID=D.DATA_SOURCE_ID
WHERE P.POLICY_ID IS NULL;

SELECT 'ORIGENES_SGA_DHT' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=2 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_ORIGIN
WHERE UPPER(ORIGIN_CODE) IN ('SGA','DHT');

SELECT 'OBJETOS_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND STATUS <> 'VALID';

SELECT 'USUARIO_PRESERVADO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)>=1 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER;

SELECT 'AUTH_PRESERVADA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)>=1 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER_AUTH;

SELECT 'SISGAV2_PROTEGIDA' CONTROL,
       CASE WHEN COUNT(*)=1 THEN 'EXISTE - FUERA DEL PARCHE'
            ELSE 'NO EXISTE - SIN ACCION' END ESTADO
FROM USER_TABLES WHERE TABLE_NAME='SISGAV2';
