/* ============================================================
   BILLING ONE v0.2.1
   MIGRACION v0.2.0 -> v0.2.1
   00_PRECHECK.sql - SOLO LECTURA / DBEAVER

   Este parche está preparado para el estado actual recién instalado:
   seguridad con usuario, pero contexto/integraciones aún sin configuración.

   Para aplicar 10_APPLY.sql, todos los conteos de abajo deben ser 0.
   NO consulta ni modifica SISGAV2.
   ============================================================ */

SELECT 'RM_CFACT_SCOPE' TABLA, COUNT(*) FILAS FROM RM_CFACT_SCOPE
UNION ALL SELECT 'RM_CFACT_USER_SCOPE', COUNT(*) FROM RM_CFACT_USER_SCOPE
UNION ALL SELECT 'RM_CFACT_CONNECTION_SCOPE', COUNT(*) FROM RM_CFACT_CONNECTION_SCOPE
UNION ALL SELECT 'RM_CFACT_SOURCE_SCOPE', COUNT(*) FROM RM_CFACT_SOURCE_SCOPE
UNION ALL SELECT 'RM_CFACT_DATA_SOURCE', COUNT(*) FROM RM_CFACT_DATA_SOURCE
UNION ALL SELECT 'RM_CFACT_DATA_SOURCE_PARAM', COUNT(*) FROM RM_CFACT_DATA_SOURCE_PARAM
UNION ALL SELECT 'RM_CFACT_EXTRACTION_RUN', COUNT(*) FROM RM_CFACT_EXTRACTION_RUN
UNION ALL SELECT 'RM_CFACT_INTEGRATION_CALL', COUNT(*) FROM RM_CFACT_INTEGRATION_CALL
UNION ALL SELECT 'RM_CFACT_CONNECTION_TEST', COUNT(*) FROM RM_CFACT_CONNECTION_TEST
UNION ALL SELECT 'RM_CFACT_DOM', COUNT(*) FROM RM_CFACT_DOM
UNION ALL SELECT 'RM_CFACT_CYCLE', COUNT(*) FROM RM_CFACT_CYCLE
ORDER BY 1;

SELECT 'USUARIOS_V02' CONTROL, COUNT(*) CANTIDAD FROM RM_CFACT_USER;
SELECT 'USUARIOS_AUTH_V02' CONTROL, COUNT(*) CANTIDAD FROM RM_CFACT_USER_AUTH;

SELECT 'TABLAS_NUEVAS_EXISTENTES' CONTROL, COUNT(*) CANTIDAD
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'RM_CFACT_ORIGIN','RM_CFACT_EMISSION_TYPE','RM_CFACT_FLOW',
 'RM_CFACT_EMISSION_STATUS','RM_CFACT_ISSUE'
);
