/* ============================================================
   BILLING ONE v0.2.1
   MIGRACION v0.2.0 -> v0.2.1
   20_VALIDATE.sql - SOLO LECTURA / DBEAVER
   ============================================================ */

SELECT 'TABLAS_NUEVAS' CONTROL, COUNT(*) REAL, 5 ESPERADO,
       CASE WHEN COUNT(*)=5 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'RM_CFACT_ORIGIN','RM_CFACT_EMISSION_TYPE','RM_CFACT_FLOW',
 'RM_CFACT_EMISSION_STATUS','RM_CFACT_ISSUE'
);

SELECT 'TABLAS_DOM_CYCLE_RETIRADAS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN ('RM_CFACT_DOM','RM_CFACT_CYCLE');

SELECT 'COLUMNAS_SCOPE_V021' CONTROL, COUNT(*) REAL, 5 ESPERADO,
       CASE WHEN COUNT(*)=5 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME='RM_CFACT_SCOPE'
  AND COLUMN_NAME IN ('ISSUER_ID','BUSINESS_ID','ORIGIN_ID','EMISSION_TYPE_ID','FLOW_ID');

SELECT 'COLUMNAS_SCOPE_LEGACY' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME='RM_CFACT_SCOPE'
  AND COLUMN_NAME IN ('COMPANY_ID','DOM_ID','CYCLE_ID');

SELECT 'TIPOS_EMISION_BASE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=2 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EMISSION_TYPE
WHERE EMISSION_TYPE_CODE IN ('MASIVO','ONLINE');

SELECT 'ORIGENES_BASE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=4 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_ORIGIN
WHERE ORIGIN_CODE IN ('ANDES','AMDOCS','SAP','ACEPTA');

SELECT 'USUARIO_PRESERVADO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)>=1 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER;

SELECT 'AUTH_PRESERVADA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)>=1 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER_AUTH;

SELECT 'SCOPE_VACIO_POST_PATCH' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE;

SELECT 'OBJETOS_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND STATUS <> 'VALID';

SELECT 'SISGAV2_PROTEGIDA' CONTROL,
       CASE WHEN COUNT(*)=1 THEN 'EXISTE - FUERA DEL PARCHE'
            ELSE 'NO EXISTE - SIN ACCION' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME='SISGAV2';
