/* BILLING ONE - migración v0.1 -> v0.2
   CONTEOS REALES antes de cualquier DROP. SOLO LECTURA.
   SISGAV2 está excluida deliberadamente. */

SELECT 'RM_CFACT_AI_PROVIDER' TABLA, COUNT(*) FILAS FROM RM_CFACT_AI_PROVIDER
UNION ALL SELECT 'RM_CFACT_AUDIT_LOG', COUNT(*) FROM RM_CFACT_AUDIT_LOG
UNION ALL SELECT 'RM_CFACT_DATA_SOURCE', COUNT(*) FROM RM_CFACT_DATA_SOURCE
UNION ALL SELECT 'RM_CFACT_EXTRACTION_RUN', COUNT(*) FROM RM_CFACT_EXTRACTION_RUN
UNION ALL SELECT 'RM_CFACT_INTEGRATION_CALL', COUNT(*) FROM RM_CFACT_INTEGRATION_CALL
UNION ALL SELECT 'RM_CFACT_USER', COUNT(*) FROM RM_CFACT_USER
UNION ALL SELECT 'SIS_AI_PROVIDER', COUNT(*) FROM SIS_AI_PROVIDER
UNION ALL SELECT 'SIS_AUDIT_LOG', COUNT(*) FROM SIS_AUDIT_LOG
UNION ALL SELECT 'SIS_DATA_SOURCE', COUNT(*) FROM SIS_DATA_SOURCE
UNION ALL SELECT 'SIS_EXTRACTION_RUN', COUNT(*) FROM SIS_EXTRACTION_RUN
UNION ALL SELECT 'SIS_INTEGRATION_CALL', COUNT(*) FROM SIS_INTEGRATION_CALL
ORDER BY 1;
