/* ============================================================
   BILLING ONE / SIS-FACT
   MIGRACION v0.1 -> v0.2
   PASO 2 - RESTAURAR USUARIO v0.1 EN MODELO DE SEGURIDAD v0.2

   VERSION DBEAVER / ORACLE SQL PLANO
   - Sin DECLARE / BEGIN / END /
   - Idempotente para el usuario ya restaurado
   - RM_CFACT_USER_V01 se conserva hasta validar el login web
   ============================================================ */

/* 1) Validacion previa: debe existir 1 usuario en staging. */
SELECT COUNT(*) AS USUARIOS_STAGING
FROM RM_CFACT_USER_V01;

/* 2) Validacion previa: el rol del usuario staging debe existir en v0.2. */
SELECT
    U.USERNAME,
    U.ROLE_CODE AS ROLE_V01,
    R.ROLE_ID,
    R.ROLE_CODE AS ROLE_V02,
    R.ACTIVE AS ROLE_ACTIVE
FROM RM_CFACT_USER_V01 U
LEFT JOIN RM_CFACT_ROLE R
  ON UPPER(R.ROLE_CODE) = UPPER(U.ROLE_CODE);

/* 3) Restaurar el usuario en RM_CFACT_USER si aun no existe. */
INSERT INTO RM_CFACT_USER (
    USERNAME,
    DISPLAY_NAME,
    EMAIL,
    ROLE_ID,
    PASSWORD_HASH,
    ACTIVE,
    CREATED_AT,
    CREATED_BY,
    UPDATED_AT,
    UPDATED_BY
)
SELECT
    U.USERNAME,
    U.DISPLAY_NAME,
    U.EMAIL,
    R.ROLE_ID,
    U.PASSWORD_HASH,
    U.ACTIVE,
    CAST(U.CREATED_AT AS TIMESTAMP),
    U.CREATED_BY,
    CAST(U.UPDATED_AT AS TIMESTAMP),
    U.UPDATED_BY
FROM RM_CFACT_USER_V01 U
JOIN RM_CFACT_ROLE R
  ON UPPER(R.ROLE_CODE) = UPPER(U.ROLE_CODE)
 AND R.ACTIVE = 'Y'
WHERE NOT EXISTS (
    SELECT 1
    FROM RM_CFACT_USER N
    WHERE LOWER(N.USERNAME) = LOWER(U.USERNAME)
);

/* 4) Crear la configuracion de autenticacion v0.2 si aun no existe. */
INSERT INTO RM_CFACT_USER_AUTH (
    USER_ID,
    AUTH_TYPE,
    LDAP_USERNAME,
    SESSION_VERSION,
    FAILED_ATTEMPTS,
    UPDATED_AT
)
SELECT
    N.USER_ID,
    U.AUTH_TYPE,
    CASE
        WHEN UPPER(U.AUTH_TYPE) = 'LDAP' THEN U.USERNAME
        ELSE NULL
    END,
    1,
    0,
    SYSTIMESTAMP
FROM RM_CFACT_USER_V01 U
JOIN RM_CFACT_USER N
  ON LOWER(N.USERNAME) = LOWER(U.USERNAME)
WHERE NOT EXISTS (
    SELECT 1
    FROM RM_CFACT_USER_AUTH A
    WHERE A.USER_ID = N.USER_ID
);

COMMIT;

/* 5) Validacion del usuario migrado. */
SELECT
    U.USER_ID,
    U.USERNAME,
    U.DISPLAY_NAME,
    U.EMAIL,
    R.ROLE_CODE,
    U.ACTIVE AS USER_ACTIVE,
    A.AUTH_TYPE,
    A.LDAP_USERNAME,
    A.SESSION_VERSION,
    A.FAILED_ATTEMPTS,
    A.LOCKED_UNTIL,
    A.LAST_LOGIN_SUCCESS,
    A.LAST_LOGIN_FAILURE
FROM RM_CFACT_USER U
JOIN RM_CFACT_ROLE R
  ON R.ROLE_ID = U.ROLE_ID
JOIN RM_CFACT_USER_AUTH A
  ON A.USER_ID = U.USER_ID
ORDER BY U.USER_ID;

/* 6) Resumen esperado: 1 / 1 / 1. */
SELECT
    (SELECT COUNT(*) FROM RM_CFACT_USER_V01) AS USUARIO_STAGING,
    (SELECT COUNT(*) FROM RM_CFACT_USER) AS USUARIO_V02,
    (SELECT COUNT(*) FROM RM_CFACT_USER_AUTH) AS AUTH_V02
FROM DUAL;
