/* ============================================================
   BILLING ONE / SIS-FACT v0.2.0
   00_DIAGNOSTICO_PREVIO.sql
   SOLO LECTURA - compatible con DBeaver.
   No borra, crea ni altera objetos.
   SISGAV2 queda expresamente fuera del alcance.
   ============================================================ */

SELECT USER AS CONNECTED_USER, SYSDATE AS DATABASE_DATETIME FROM DUAL;

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS, CREATED, LAST_DDL_TIME
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
   OR OBJECT_NAME IN (
       'SIS_DATA_SOURCE','SIS_EXTRACTION_RUN','SIS_INTEGRATION_CALL',
       'SIS_AUDIT_LOG','SIS_AI_PROVIDER','SIS_USER'
   )
ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT TABLE_NAME, NUM_ROWS, LAST_ANALYZED
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
   OR TABLE_NAME IN (
       'SIS_DATA_SOURCE','SIS_EXTRACTION_RUN','SIS_INTEGRATION_CALL',
       'SIS_AUDIT_LOG','SIS_AI_PROVIDER','SIS_USER'
   )
ORDER BY TABLE_NAME;

SELECT TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH,
       DATA_PRECISION, DATA_SCALE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
   OR TABLE_NAME IN (
       'SIS_DATA_SOURCE','SIS_EXTRACTION_RUN','SIS_INTEGRATION_CALL',
       'SIS_AUDIT_LOG','SIS_AI_PROVIDER','SIS_USER'
   )
ORDER BY TABLE_NAME, COLUMN_ID;

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
   OR TABLE_NAME IN (
       'SIS_DATA_SOURCE','SIS_EXTRACTION_RUN','SIS_INTEGRATION_CALL',
       'SIS_AUDIT_LOG','SIS_AI_PROVIDER','SIS_USER'
   )
ORDER BY TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME;

SELECT TABLE_NAME, INDEX_NAME, UNIQUENESS, STATUS, INDEX_TYPE
FROM USER_INDEXES
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
   OR TABLE_NAME IN (
       'SIS_DATA_SOURCE','SIS_EXTRACTION_RUN','SIS_INTEGRATION_CALL',
       'SIS_AUDIT_LOG','SIS_AI_PROVIDER','SIS_USER'
   )
ORDER BY TABLE_NAME, INDEX_NAME;

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND STATUS <> 'VALID'
ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT 'SISGAV2_PROTEGIDA' AS CONTROL,
       CASE WHEN EXISTS (SELECT 1 FROM USER_TABLES WHERE TABLE_NAME='SISGAV2')
            THEN 'EXISTE - NO TOCAR' ELSE 'NO EXISTE' END AS ESTADO
FROM DUAL;
