-- SIS-FACT / Billing One
-- Core de integracion.
-- Regla de naming: todas las tablas propias del sistema comienzan con RM_CFACT_.

CREATE TABLE rm_cfact_data_source (
    data_source_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    source_code         VARCHAR2(80) NOT NULL,
    source_name         VARCHAR2(200) NOT NULL,
    source_type         VARCHAR2(40) NOT NULL,
    source_role         VARCHAR2(60) NOT NULL,
    connection_key      VARCHAR2(120) NOT NULL,
    priority_order      NUMBER DEFAULT 100 NOT NULL,
    active              CHAR(1) DEFAULT 'Y' NOT NULL,
    health_status       VARCHAR2(40),
    last_success_at     DATE,
    created_at          DATE DEFAULT SYSDATE NOT NULL,
    updated_at          DATE,
    CONSTRAINT uk_rm_cfact_data_source_code UNIQUE (source_code),
    CONSTRAINT ck_rm_cfact_data_source_active CHECK (active IN ('Y','N'))
);

CREATE TABLE rm_cfact_extraction_run (
    extraction_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data_source_id      NUMBER NOT NULL,
    extraction_type     VARCHAR2(80) NOT NULL,
    period_code         VARCHAR2(20),
    flow_code           VARCHAR2(80),
    scope_code          VARCHAR2(80),
    execution_code      VARCHAR2(120),
    started_at          DATE DEFAULT SYSDATE NOT NULL,
    finished_at         DATE,
    rows_read           NUMBER DEFAULT 0,
    rows_loaded         NUMBER DEFAULT 0,
    rows_rejected       NUMBER DEFAULT 0,
    status              VARCHAR2(40) DEFAULT 'RUNNING' NOT NULL,
    error_message       VARCHAR2(4000),
    query_version       VARCHAR2(80),
    CONSTRAINT fk_rm_cfact_ext_ds FOREIGN KEY (data_source_id)
        REFERENCES rm_cfact_data_source(data_source_id)
);

CREATE TABLE rm_cfact_integration_call (
    integration_call_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data_source_id      NUMBER,
    correlation_id      VARCHAR2(120),
    endpoint_name       VARCHAR2(120),
    operation_name      VARCHAR2(120),
    started_at          DATE DEFAULT SYSDATE NOT NULL,
    finished_at         DATE,
    response_time_ms    NUMBER,
    technical_status    VARCHAR2(40),
    business_status     VARCHAR2(80),
    http_status         NUMBER,
    response_code       VARCHAR2(120),
    retry_number        NUMBER DEFAULT 0,
    request_hash        VARCHAR2(200),
    error_message       VARCHAR2(4000),
    CONSTRAINT fk_rm_cfact_call_ds FOREIGN KEY (data_source_id)
        REFERENCES rm_cfact_data_source(data_source_id)
);

CREATE TABLE rm_cfact_audit_log (
    audit_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_at            DATE DEFAULT SYSDATE NOT NULL,
    username            VARCHAR2(120),
    module_name         VARCHAR2(120),
    action_name         VARCHAR2(120),
    entity_name         VARCHAR2(120),
    entity_id           VARCHAR2(120),
    detail              CLOB,
    client_ip           VARCHAR2(80)
);

CREATE TABLE rm_cfact_ai_provider (
    ai_provider_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    provider_code       VARCHAR2(80) NOT NULL,
    provider_name       VARCHAR2(200) NOT NULL,
    provider_type       VARCHAR2(40) NOT NULL,
    base_url            VARCHAR2(500),
    model_name          VARCHAR2(200),
    active              CHAR(1) DEFAULT 'N' NOT NULL,
    created_at          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_rm_cfact_ai_provider_code UNIQUE (provider_code),
    CONSTRAINT ck_rm_cfact_ai_provider_active CHECK (active IN ('Y','N'))
);

CREATE INDEX ix_rm_cfact_ext_period ON rm_cfact_extraction_run(period_code, status);
CREATE INDEX ix_rm_cfact_call_corr ON rm_cfact_integration_call(correlation_id);
CREATE INDEX ix_rm_cfact_audit_user ON rm_cfact_audit_log(username, event_at);

COMMENT ON TABLE rm_cfact_data_source IS 'Catalogo de fuentes de datos integradas a SIS-FACT.';
COMMENT ON TABLE rm_cfact_extraction_run IS 'Registro de ejecuciones de extraccion y carga.';
COMMENT ON TABLE rm_cfact_integration_call IS 'Trazabilidad de llamadas REST, SOAP u otras integraciones.';
COMMENT ON TABLE rm_cfact_audit_log IS 'Auditoria transversal de acciones del sistema.';
COMMENT ON TABLE rm_cfact_ai_provider IS 'Configuracion de proveedores de analitica o IA.';

COMMIT;
