-- SIS-FACT / Billing One v0.1.0
-- Fuentes base. Ajustar connection_key según config.ini real.

INSERT INTO SIS_DATA_SOURCE (SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, SYSTEM_ROLE, CONNECTION_KEY, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('ORACLE_BILLING', 'Oracle Billing', 'ORACLE', 'BILLING', 'oracle_billing_one', 10, 'S');

INSERT INTO SIS_DATA_SOURCE (SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, SYSTEM_ROLE, CONNECTION_KEY, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('MSSQL_FACT', 'SQL Server FACT', 'SQLSERVER', 'BILLING', 'sqlserver_fact', 20, 'S');

INSERT INTO SIS_DATA_SOURCE (SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, SYSTEM_ROLE, CONNECTION_KEY, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('FACTURADOR_REST', 'Facturador REST', 'REST', 'INVOICER', 'rest_default', 30, 'S');

INSERT INTO SIS_DATA_SOURCE (SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, SYSTEM_ROLE, CONNECTION_KEY, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('FACTURADOR_SOAP', 'Facturador SOAP', 'SOAP', 'INVOICER', 'soap_default', 40, 'S');

INSERT INTO SIS_DATA_SOURCE (SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, SYSTEM_ROLE, CONNECTION_KEY, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('SII_RCV', 'SII Registro de Ventas', 'FILE', 'TAX', 'sii_file', 50, 'S');

INSERT INTO SIS_DATA_SOURCE (SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, SYSTEM_ROLE, CONNECTION_KEY, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('BILLING_COMPARE', 'Billing Compare', 'CONTROL_ENGINE', 'CONTROL_ENGINE', 'billing_compare', 60, 'S');

COMMIT;
