-- SIS-FACT / Billing One
-- Seguridad base: usuarios locales de autorización.
-- LDAP se usa solo en tiempo de login para autenticar la contraseña corporativa.
-- Regla de naming: todas las tablas propias del sistema comienzan con RM_CFACT_.

CREATE TABLE rm_cfact_user (
    user_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(120) NOT NULL,
    display_name   VARCHAR2(200) NOT NULL,
    email          VARCHAR2(200),
    role_code      VARCHAR2(50) DEFAULT 'VIEWER' NOT NULL,
    auth_type      VARCHAR2(20) DEFAULT 'LDAP' NOT NULL,
    active         CHAR(1) DEFAULT 'Y' NOT NULL,
    password_hash  VARCHAR2(500),
    created_at     DATE DEFAULT SYSDATE NOT NULL,
    created_by     VARCHAR2(120),
    updated_at     DATE,
    updated_by     VARCHAR2(120),
    CONSTRAINT uk_rm_cfact_user_username UNIQUE (username),
    CONSTRAINT ck_rm_cfact_user_active CHECK (active IN ('Y','N')),
    CONSTRAINT ck_rm_cfact_user_auth_type CHECK (auth_type IN ('LDAP','LOCAL','SERVICE'))
);

CREATE INDEX ix_rm_cfact_user_role ON rm_cfact_user(role_code);
CREATE INDEX ix_rm_cfact_user_auth ON rm_cfact_user(auth_type, active);

COMMENT ON TABLE rm_cfact_user IS 'Usuarios SIS-FACT. La existencia local autoriza acceso; LDAP autentica credencial corporativa.';
COMMENT ON COLUMN rm_cfact_user.auth_type IS 'LDAP: valida contraseña contra LDAP. LOCAL: valida password_hash. SERVICE: reservado para integraciones.';
COMMENT ON COLUMN rm_cfact_user.password_hash IS 'Solo se usa para usuarios LOCAL. No aplica a usuarios LDAP.';

-- Usuario LDAP de ejemplo. Cambiar o eliminar según ambiente.
-- INSERT INTO rm_cfact_user (username, display_name, email, role_code, auth_type, active, created_by)
-- VALUES ('usuario.corporativo', 'Usuario Corporativo', 'usuario.corporativo@empresa.local', 'ADMIN', 'LDAP', 'Y', 'INSTALL');

COMMIT;
