/* BILLING ONE v0.2.0 - 11_VALIDAR_SECURITY.sql - SOLO LECTURA */

SELECT 'SECURITY_TABLES' CONTROL, COUNT(*) REAL, 8 ESPERADO,
       CASE WHEN COUNT(*)=8 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'RM_CFACT_ROLE','RM_CFACT_PERMISSION','RM_CFACT_ROLE_PERMISSION','RM_CFACT_USER',
 'RM_CFACT_USER_AUTH','RM_CFACT_USER_PERMISSION','RM_CFACT_LOGIN_RATE_LIMIT','RM_CFACT_AUDIT_LOG'
);

SELECT 'ROLES_BASE' CONTROL, COUNT(*) REAL, 5 ESPERADO,
       CASE WHEN COUNT(*)=5 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_ROLE
WHERE ROLE_CODE IN ('ADMIN','CONFIG','OPERADOR','AUDITOR','VIEWER');

SELECT 'PERMISOS_BASE' CONTROL, COUNT(*) REAL, 9 ESPERADO,
       CASE WHEN COUNT(*)=9 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_PERMISSION;

SELECT 'COLUMNAS_SEGURIDAD_CRITICAS' CONTROL, COUNT(*) REAL, 8 ESPERADO,
       CASE WHEN COUNT(*)=8 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TAB_COLUMNS
WHERE (TABLE_NAME='RM_CFACT_USER_AUTH' AND COLUMN_NAME IN ('AUTH_TYPE','LDAP_USERNAME','SESSION_VERSION','FAILED_ATTEMPTS','LOCKED_UNTIL'))
   OR (TABLE_NAME='RM_CFACT_LOGIN_RATE_LIMIT' AND COLUMN_NAME IN ('FAILED_ATTEMPTS','LOCKED_UNTIL'))
   OR (TABLE_NAME='RM_CFACT_USER' AND COLUMN_NAME='ROLE_ID');

SELECT 'FK_SEGURIDAD' CONTROL, COUNT(*) REAL, 7 ESPERADO,
       CASE WHEN COUNT(*)=7 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN (
 'FK_RMCF_RP_ROLE','FK_RMCF_RP_PERM','FK_RMCF_USER_ROLE','FK_RMCF_UA_USER',
 'FK_RMCF_UP_USER','FK_RMCF_UP_PERM','FK_RMCF_AUD_USER'
) AND CONSTRAINT_TYPE='R' AND STATUS='ENABLED' AND VALIDATED='VALIDATED';

SELECT 'INDICES_SEGURIDAD_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE INDEX_NAME IN ('IX_RMCF_USER_ROLE','IX_RMCF_UA_LOCK','IX_RMCF_AUD_EVENT','IX_RMCF_AUD_USER')
  AND STATUS <> 'VALID';

SELECT 'USUARIOS_SIN_AUTH' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER U
LEFT JOIN RM_CFACT_USER_AUTH A ON A.USER_ID=U.USER_ID
WHERE A.USER_ID IS NULL;

SELECT 'USUARIOS_ROL_INVALIDO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER U
LEFT JOIN RM_CFACT_ROLE R ON R.ROLE_ID=U.ROLE_ID
WHERE R.ROLE_ID IS NULL;

SELECT 'ORIGENES_BLOQUEADOS' CONTROL, COUNT(*) CANTIDAD
FROM RM_CFACT_LOGIN_RATE_LIMIT
WHERE LOCKED_UNTIL > SYSTIMESTAMP;
