/* BILLING ONE v0.2.0 - 12_BOOTSTRAP_ADMIN.sql
   Ejecutar solo después de 10_SECURITY_BASE.sql.
   Reemplazar los tres valores REEMPLAZAR_... antes de ejecutar.
   No contiene ni solicita password LDAP. */

DECLARE
    V_USERNAME      VARCHAR2(120) := 'REEMPLAZAR_USUARIO';
    V_DISPLAY_NAME  VARCHAR2(200) := 'REEMPLAZAR_NOMBRE';
    V_EMAIL         VARCHAR2(200) := 'REEMPLAZAR_CORREO';
    V_ROLE_ID       NUMBER;
    V_USER_ID       NUMBER;
BEGIN
    IF V_USERNAME = 'REEMPLAZAR_USUARIO' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Debe reemplazar V_USERNAME, V_DISPLAY_NAME y V_EMAIL.');
    END IF;

    SELECT ROLE_ID INTO V_ROLE_ID
    FROM RM_CFACT_ROLE
    WHERE ROLE_CODE='ADMIN' AND ACTIVE='Y';

    INSERT INTO RM_CFACT_USER (
        USERNAME, DISPLAY_NAME, EMAIL, ROLE_ID, ACTIVE, CREATED_BY
    ) VALUES (
        LOWER(V_USERNAME), V_DISPLAY_NAME, V_EMAIL, V_ROLE_ID, 'Y', 'INSTALL'
    );

    SELECT USER_ID INTO V_USER_ID
    FROM RM_CFACT_USER
    WHERE LOWER(USERNAME)=LOWER(V_USERNAME);

    INSERT INTO RM_CFACT_USER_AUTH (
        USER_ID, AUTH_TYPE, LDAP_USERNAME, SESSION_VERSION, FAILED_ATTEMPTS
    ) VALUES (
        V_USER_ID, 'LDAP', LOWER(V_USERNAME), 1, 0
    );

    COMMIT;
END;
/

SELECT U.USER_ID, U.USERNAME, U.DISPLAY_NAME, R.ROLE_CODE,
       A.AUTH_TYPE, U.ACTIVE, A.SESSION_VERSION
FROM RM_CFACT_USER U
JOIN RM_CFACT_ROLE R ON R.ROLE_ID=U.ROLE_ID
JOIN RM_CFACT_USER_AUTH A ON A.USER_ID=U.USER_ID
ORDER BY U.USER_ID;
