/* BILLING ONE v0.2.1 - 21_VALIDAR_CONTEXT.sql - SOLO LECTURA */

SELECT 'CONTEXT_TABLES' CONTROL, COUNT(*) REAL, 8 ESPERADO,
       CASE WHEN COUNT(*)=8 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'RM_CFACT_COMPANY','RM_CFACT_ISSUER','RM_CFACT_BUSINESS','RM_CFACT_ORIGIN',
 'RM_CFACT_EMISSION_TYPE','RM_CFACT_FLOW','RM_CFACT_SCOPE','RM_CFACT_USER_SCOPE'
);

SELECT 'FK_CONTEXT' CONTROL, COUNT(*) REAL, 10 ESPERADO,
       CASE WHEN COUNT(*)=10 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN (
 'FK_RMCF_ISS_COMP','FK_RMCF_FLOW_ORIGIN','FK_RMCF_FLOW_EMTYPE',
 'FK_RMCF_SC_ISS','FK_RMCF_SC_BUS','FK_RMCF_SC_ORIGIN','FK_RMCF_SC_EMTYPE','FK_RMCF_SC_FLOW_CTX',
 'FK_RMCF_US_USER','FK_RMCF_US_SCOPE'
) AND CONSTRAINT_TYPE='R' AND STATUS='ENABLED' AND VALIDATED='VALIDATED';

SELECT 'SCOPES_INCOMPLETOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE
WHERE ISSUER_ID IS NULL
   OR BUSINESS_ID IS NULL
   OR ORIGIN_ID IS NULL
   OR EMISSION_TYPE_ID IS NULL;

SELECT 'SCOPES_FLUJO_INCONSISTENTE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE S
JOIN RM_CFACT_FLOW F ON F.FLOW_ID=S.FLOW_ID
WHERE S.FLOW_ID IS NOT NULL
  AND (F.ORIGIN_ID<>S.ORIGIN_ID OR F.EMISSION_TYPE_ID<>S.EMISSION_TYPE_ID);

SELECT 'SCOPES_FECHA_INVALIDA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE
WHERE VALID_FROM IS NOT NULL AND VALID_TO IS NOT NULL AND VALID_TO < VALID_FROM;

SELECT 'USER_SCOPE_HUERFANO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER_SCOPE US
LEFT JOIN RM_CFACT_USER U ON U.USER_ID=US.USER_ID
LEFT JOIN RM_CFACT_SCOPE S ON S.SCOPE_ID=US.SCOPE_ID
WHERE U.USER_ID IS NULL OR S.SCOPE_ID IS NULL;

SELECT 'CATALOGOS_BASE' CONTROL,
       (SELECT COUNT(*) FROM RM_CFACT_EMISSION_TYPE WHERE EMISSION_TYPE_CODE IN ('MASIVO','ONLINE')) TIPOS_BASE,
       (SELECT COUNT(*) FROM RM_CFACT_ORIGIN WHERE ORIGIN_CODE IN ('ANDES','AMDOCS','SAP','ACEPTA')) ORIGENES_BASE
FROM DUAL;

SELECT 'INDICES_CONTEXT_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE INDEX_NAME IN ('IX_RMCF_ISS_COMP','IX_RMCF_FLOW_CTX','IX_RMCF_SC_CTX','IX_RMCF_US_SCOPE')
  AND STATUS <> 'VALID';
