/* BILLING ONE v0.2.0 - 21_VALIDAR_CONTEXT.sql - SOLO LECTURA */

SELECT 'CONTEXT_TABLES' CONTROL, COUNT(*) REAL, 7 ESPERADO,
       CASE WHEN COUNT(*)=7 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'RM_CFACT_COMPANY','RM_CFACT_ISSUER','RM_CFACT_BUSINESS','RM_CFACT_DOM',
 'RM_CFACT_CYCLE','RM_CFACT_SCOPE','RM_CFACT_USER_SCOPE'
);

SELECT 'FK_CONTEXT' CONTROL, COUNT(*) REAL, 8 ESPERADO,
       CASE WHEN COUNT(*)=8 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN (
 'FK_RMCF_ISS_COMP','FK_RMCF_SC_COMP','FK_RMCF_SC_ISS','FK_RMCF_SC_BUS',
 'FK_RMCF_SC_DOM','FK_RMCF_SC_CYC','FK_RMCF_US_USER','FK_RMCF_US_SCOPE'
) AND CONSTRAINT_TYPE='R' AND STATUS='ENABLED' AND VALIDATED='VALIDATED';

SELECT 'SCOPES_ISSUER_OTRA_EMPRESA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE S
JOIN RM_CFACT_ISSUER I ON I.ISSUER_ID=S.ISSUER_ID
WHERE S.COMPANY_ID <> I.COMPANY_ID;

SELECT 'SCOPES_FECHA_INVALIDA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE
WHERE VALID_FROM IS NOT NULL AND VALID_TO IS NOT NULL AND VALID_TO < VALID_FROM;

SELECT 'USER_SCOPE_HUERFANO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER_SCOPE US
LEFT JOIN RM_CFACT_USER U ON U.USER_ID=US.USER_ID
LEFT JOIN RM_CFACT_SCOPE S ON S.SCOPE_ID=US.SCOPE_ID
WHERE U.USER_ID IS NULL OR S.SCOPE_ID IS NULL;

SELECT 'INDICES_CONTEXT_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE INDEX_NAME IN ('IX_RMCF_ISS_COMP','IX_RMCF_SC_CTX','IX_RMCF_US_SCOPE')
  AND STATUS <> 'VALID';
