/* BILLING ONE v0.2.1 - 31_VALIDAR_INTEGRATION.sql - SOLO LECTURA */

SELECT 'INTEGRATION_TABLES' CONTROL, COUNT(*) REAL, 8 ESPERADO,
       CASE WHEN COUNT(*)=8 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'RM_CFACT_CONNECTION','RM_CFACT_CONNECTION_SCOPE','RM_CFACT_DATA_SOURCE',
 'RM_CFACT_DATA_SOURCE_PARAM','RM_CFACT_SOURCE_SCOPE','RM_CFACT_EXTRACTION_RUN',
 'RM_CFACT_INTEGRATION_CALL','RM_CFACT_CONNECTION_TEST'
);

SELECT 'FUENTES_SIN_CONEXION' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_CONNECTION C ON C.CONNECTION_ID=D.CONNECTION_ID
WHERE C.CONNECTION_ID IS NULL;

SELECT 'FUENTES_ACTIVAS_SIN_SCOPE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_SOURCE_SCOPE S ON S.DATA_SOURCE_ID=D.DATA_SOURCE_ID AND S.ACTIVE='Y'
WHERE D.ACTIVE='Y' AND S.SOURCE_SCOPE_ID IS NULL;

SELECT 'SOURCE_SCOPE_FUERA_CONN' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SOURCE_SCOPE SS
JOIN RM_CFACT_DATA_SOURCE D ON D.DATA_SOURCE_ID=SS.DATA_SOURCE_ID
WHERE SS.ACTIVE='Y'
  AND EXISTS (
      SELECT 1 FROM RM_CFACT_CONNECTION_SCOPE CS0
      WHERE CS0.CONNECTION_ID=D.CONNECTION_ID AND CS0.ACTIVE='Y'
  )
  AND NOT EXISTS (
      SELECT 1 FROM RM_CFACT_CONNECTION_SCOPE CS
      WHERE CS.CONNECTION_ID=D.CONNECTION_ID
        AND CS.SCOPE_ID=SS.SCOPE_ID
        AND CS.ACTIVE='Y'
  );

SELECT 'CONFIG_CON_POSIBLE_SECRETO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_CONNECTION
WHERE CONFIG_JSON IS NOT NULL
  AND (
       DBMS_LOB.INSTR(CONFIG_JSON, 'password') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'PASSWORD') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'secret') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'SECRET') > 0
  );

SELECT 'EXTRACCIONES_FILAS_INVALIDAS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EXTRACTION_RUN
WHERE ROWS_READ < 0 OR ROWS_LOADED < 0 OR ROWS_REJECTED < 0;

SELECT 'INDICES_INTEGRACION_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE INDEX_NAME IN (
 'IX_RMCF_CS_SCOPE','IX_RMCF_DS_CONN','IX_RMCF_SS_SCOPE','IX_RMCF_ER_SRC',
 'IX_RMCF_ER_CORR','IX_RMCF_IC_CORR','IX_RMCF_CT_CONN'
) AND STATUS <> 'VALID';
