/* BILLING ONE v0.2.1 - 41_VALIDAR_OPERATIONAL.sql - SOLO LECTURA */

SELECT 'OPERATIONAL_TABLES' CONTROL, COUNT(*) REAL, 2 ESPERADO,
       CASE WHEN COUNT(*)=2 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN ('RM_CFACT_EMISSION_STATUS','RM_CFACT_ISSUE');

SELECT 'ESTADOS_PCT_INVALIDO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EMISSION_STATUS
WHERE COMPLETENESS_PCT IS NOT NULL
  AND (COMPLETENESS_PCT < 0 OR COMPLETENESS_PCT > 100);

SELECT 'ESTADOS_QTY_INVALIDA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EMISSION_STATUS
WHERE EXPECTED_QTY < 0 OR EMITTED_QTY < 0 OR REJECTED_QTY < 0 OR ISSUE_QTY < 0;

SELECT 'ESTADOS_SCOPE_HUERFANO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EMISSION_STATUS E
LEFT JOIN RM_CFACT_SCOPE S ON S.SCOPE_ID=E.SCOPE_ID
WHERE S.SCOPE_ID IS NULL;

SELECT 'ISSUES_HUERFANOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_ISSUE I
LEFT JOIN RM_CFACT_EMISSION_STATUS E ON E.EMISSION_STATUS_ID=I.EMISSION_STATUS_ID
WHERE E.EMISSION_STATUS_ID IS NULL;

SELECT 'INDICES_OPERATIONAL_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE INDEX_NAME IN ('IX_RMCF_ES_SCOPE','IX_RMCF_ES_STATUS','IX_RMCF_ISSUE_ES')
  AND STATUS <> 'VALID';
