/* BILLING ONE v0.2.4 - 51_VALIDAR_EXECUTION.sql - SOLO LECTURA */

SELECT 'EXECUTION_TABLES' CONTROL, COUNT(*) REAL, 2 ESPERADO,
       CASE WHEN COUNT(*)=2 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN ('RM_CFACT_EXECUTION_POLICY','RM_CFACT_EXECUTION_QUEUE');

SELECT 'FUENTES_SIN_POLITICA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_EXECUTION_POLICY P ON P.DATA_SOURCE_ID=D.DATA_SOURCE_ID
WHERE P.POLICY_ID IS NULL;

SELECT 'POLITICAS_PROGRAMADAS_SIN_FRECUENCIA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EXECUTION_POLICY
WHERE ACTIVE='Y'
  AND EXECUTION_MODE='SCHEDULED'
  AND FREQUENCY_TYPE IS NULL;

SELECT 'POLITICAS_EXTERNAS_SIN_EJECUTOR' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EXECUTION_POLICY
WHERE ACTIVE='Y'
  AND EXECUTION_MODE='EXTERNAL'
  AND TRIM(EXTERNAL_EXECUTOR) IS NULL;

SELECT 'COLA_SCOPE_NO_APLICA_FUENTE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EXECUTION_QUEUE Q
WHERE NOT EXISTS (
    SELECT 1 FROM RM_CFACT_SOURCE_SCOPE SS
    WHERE SS.DATA_SOURCE_ID=Q.DATA_SOURCE_ID
      AND SS.SCOPE_ID=Q.SCOPE_ID
      AND SS.ACTIVE='Y'
);

SELECT 'COLA_EN_RUNNING_SIN_INICIO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EXECUTION_QUEUE
WHERE STATUS='RUNNING' AND STARTED_AT IS NULL;

SELECT 'INDICES_EXECUTION_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE INDEX_NAME IN ('IX_RMCF_EXPOL_DUE','IX_RMCF_EXQ_PICK','IX_RMCF_EXQ_SOURCE')
  AND STATUS <> 'VALID';
