/* ============================================================
   BILLING ONE / SIS-FACT v0.2.0
   90_VALIDAR_BILLING_ONE.sql
   Certificación global greenfield - SOLO LECTURA.
   Ejecutar después de 10, 20 y 30 más sus validadores.
   ============================================================ */

SELECT 'TABLAS_BILLING_ONE' CONTROL, COUNT(*) REAL, 23 ESPERADO,
       CASE WHEN COUNT(*)=23 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'RM_CFACT_ROLE','RM_CFACT_PERMISSION','RM_CFACT_ROLE_PERMISSION','RM_CFACT_USER',
 'RM_CFACT_USER_AUTH','RM_CFACT_USER_PERMISSION','RM_CFACT_LOGIN_RATE_LIMIT','RM_CFACT_AUDIT_LOG',
 'RM_CFACT_COMPANY','RM_CFACT_ISSUER','RM_CFACT_BUSINESS','RM_CFACT_DOM',
 'RM_CFACT_CYCLE','RM_CFACT_SCOPE','RM_CFACT_USER_SCOPE',
 'RM_CFACT_CONNECTION','RM_CFACT_CONNECTION_SCOPE','RM_CFACT_DATA_SOURCE',
 'RM_CFACT_DATA_SOURCE_PARAM','RM_CFACT_SOURCE_SCOPE','RM_CFACT_EXTRACTION_RUN',
 'RM_CFACT_INTEGRATION_CALL','RM_CFACT_CONNECTION_TEST'
);

SELECT 'OBJETOS_RM_CFACT_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND STATUS <> 'VALID';

SELECT 'INDICES_RM_CFACT_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND STATUS <> 'VALID';

SELECT 'FK_RM_CFACT_NO_VALIDAS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND CONSTRAINT_TYPE='R'
  AND (STATUS <> 'ENABLED' OR VALIDATED <> 'VALIDATED');

SELECT 'USUARIOS_SIN_AUTH' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER U
LEFT JOIN RM_CFACT_USER_AUTH A ON A.USER_ID=U.USER_ID
WHERE A.USER_ID IS NULL;

SELECT 'SCOPES_ISSUER_OTRA_EMPRESA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE S
JOIN RM_CFACT_ISSUER I ON I.ISSUER_ID=S.ISSUER_ID
WHERE S.COMPANY_ID <> I.COMPANY_ID;

SELECT 'FUENTES_SIN_CONEXION' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_CONNECTION C ON C.CONNECTION_ID=D.CONNECTION_ID
WHERE C.CONNECTION_ID IS NULL;

SELECT 'FUENTES_ACTIVAS_SIN_SCOPE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_SOURCE_SCOPE S ON S.DATA_SOURCE_ID=D.DATA_SOURCE_ID AND S.ACTIVE='Y'
WHERE D.ACTIVE='Y' AND S.SOURCE_SCOPE_ID IS NULL;

SELECT 'LEGACY_SIS_FACT_SIS_PREFIX' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'SIS_DATA_SOURCE','SIS_EXTRACTION_RUN','SIS_INTEGRATION_CALL',
 'SIS_AUDIT_LOG','SIS_AI_PROVIDER','SIS_USER'
);

SELECT 'SISGAV2_PROTEGIDA' CONTROL,
       CASE WHEN COUNT(*)=1 THEN 'EXISTE - FUERA DE BILLING ONE'
            ELSE 'NO EXISTE - SIN ACCION' END ESTADO
FROM USER_TABLES WHERE TABLE_NAME='SISGAV2';
