/* ============================================================
   BILLING ONE / SIS-FACT v0.2.4
   90_VALIDAR_BILLING_ONE.sql
   Certificación global - SOLO LECTURA.
   ============================================================ */

SELECT 'TABLAS_BILLING_ONE' CONTROL, COUNT(*) REAL, 28 ESPERADO,
       CASE WHEN COUNT(*)=28 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'RM_CFACT_ROLE','RM_CFACT_PERMISSION','RM_CFACT_ROLE_PERMISSION','RM_CFACT_USER',
 'RM_CFACT_USER_AUTH','RM_CFACT_USER_PERMISSION','RM_CFACT_LOGIN_RATE_LIMIT','RM_CFACT_AUDIT_LOG',
 'RM_CFACT_COMPANY','RM_CFACT_ISSUER','RM_CFACT_BUSINESS','RM_CFACT_ORIGIN',
 'RM_CFACT_EMISSION_TYPE','RM_CFACT_FLOW','RM_CFACT_SCOPE','RM_CFACT_USER_SCOPE',
 'RM_CFACT_CONNECTION','RM_CFACT_CONNECTION_SCOPE','RM_CFACT_DATA_SOURCE',
 'RM_CFACT_DATA_SOURCE_PARAM','RM_CFACT_SOURCE_SCOPE','RM_CFACT_EXTRACTION_RUN',
 'RM_CFACT_INTEGRATION_CALL','RM_CFACT_CONNECTION_TEST',
 'RM_CFACT_EMISSION_STATUS','RM_CFACT_ISSUE',
 'RM_CFACT_EXECUTION_POLICY','RM_CFACT_EXECUTION_QUEUE'
);

SELECT 'OBJETOS_RM_CFACT_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND STATUS <> 'VALID';

SELECT 'INDICES_RM_CFACT_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND STATUS <> 'VALID';

SELECT 'FK_RM_CFACT_NO_VALIDAS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND CONSTRAINT_TYPE='R'
  AND (STATUS <> 'ENABLED' OR VALIDATED <> 'VALIDATED');

SELECT 'USUARIOS_SIN_AUTH' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER U
LEFT JOIN RM_CFACT_USER_AUTH A ON A.USER_ID=U.USER_ID
WHERE A.USER_ID IS NULL;

SELECT 'USUARIOS_ROL_INVALIDO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER U
LEFT JOIN RM_CFACT_ROLE R ON R.ROLE_ID=U.ROLE_ID
WHERE R.ROLE_ID IS NULL;

SELECT 'USUARIOS_OPERATIVOS_SIN_SCOPE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM (
    SELECT U.USER_ID
    FROM RM_CFACT_USER U
    JOIN RM_CFACT_ROLE R ON R.ROLE_ID=U.ROLE_ID
    LEFT JOIN RM_CFACT_USER_SCOPE US ON US.USER_ID=U.USER_ID
    WHERE U.ACTIVE='Y'
      AND R.ROLE_CODE IN ('OPERADOR','AUDITOR','VIEWER')
    GROUP BY U.USER_ID
    HAVING COUNT(US.SCOPE_ID)=0
);

SELECT 'USER_SCOPE_JERARQUIA_INVALIDA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER_SCOPE
WHERE (CAN_EXECUTE='Y' AND CAN_VIEW<>'Y')
   OR (CAN_CONFIGURE='Y' AND (CAN_EXECUTE<>'Y' OR CAN_VIEW<>'Y'));

SELECT 'SCOPES_INCOMPLETOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE
WHERE ISSUER_ID IS NULL OR BUSINESS_ID IS NULL OR ORIGIN_ID IS NULL OR EMISSION_TYPE_ID IS NULL;

SELECT 'SCOPES_FLUJO_INCONSISTENTE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE S
JOIN RM_CFACT_FLOW F ON F.FLOW_ID=S.FLOW_ID
WHERE S.FLOW_ID IS NOT NULL
  AND (F.ORIGIN_ID<>S.ORIGIN_ID OR F.EMISSION_TYPE_ID<>S.EMISSION_TYPE_ID);

SELECT 'FUENTES_SIN_CONEXION' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_CONNECTION C ON C.CONNECTION_ID=D.CONNECTION_ID
WHERE C.CONNECTION_ID IS NULL;

SELECT 'FUENTES_ACTIVAS_SIN_SCOPE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_SOURCE_SCOPE S ON S.DATA_SOURCE_ID=D.DATA_SOURCE_ID AND S.ACTIVE='Y'
WHERE D.ACTIVE='Y' AND S.SOURCE_SCOPE_ID IS NULL;

SELECT 'SOURCE_SCOPE_FUERA_CONN' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SOURCE_SCOPE SS
JOIN RM_CFACT_DATA_SOURCE D ON D.DATA_SOURCE_ID=SS.DATA_SOURCE_ID
WHERE SS.ACTIVE='Y'
  AND EXISTS (
      SELECT 1 FROM RM_CFACT_CONNECTION_SCOPE CS0
      WHERE CS0.CONNECTION_ID=D.CONNECTION_ID AND CS0.ACTIVE='Y'
  )
  AND NOT EXISTS (
      SELECT 1 FROM RM_CFACT_CONNECTION_SCOPE CS
      WHERE CS.CONNECTION_ID=D.CONNECTION_ID
        AND CS.SCOPE_ID=SS.SCOPE_ID
        AND CS.ACTIVE='Y'
  );

SELECT 'CONFIG_CON_POSIBLE_SECRETO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_CONNECTION
WHERE CONFIG_JSON IS NOT NULL
  AND (
       DBMS_LOB.INSTR(CONFIG_JSON, 'password') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'PASSWORD') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'secret') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'SECRET') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'token') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'TOKEN') > 0
  );

SELECT 'FUENTES_SIN_POLITICA_EJECUCION' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_EXECUTION_POLICY P ON P.DATA_SOURCE_ID=D.DATA_SOURCE_ID
WHERE P.POLICY_ID IS NULL;

SELECT 'POLITICAS_PROGRAMADAS_INVALIDAS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EXECUTION_POLICY
WHERE ACTIVE='Y'
  AND EXECUTION_MODE='SCHEDULED'
  AND FREQUENCY_TYPE IS NULL;

SELECT 'POLITICAS_EXTERNAS_SIN_EJECUTOR' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EXECUTION_POLICY
WHERE ACTIVE='Y'
  AND EXECUTION_MODE='EXTERNAL'
  AND TRIM(EXTERNAL_EXECUTOR) IS NULL;

SELECT 'COLA_SCOPE_NO_APLICA_FUENTE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EXECUTION_QUEUE Q
WHERE NOT EXISTS (
    SELECT 1 FROM RM_CFACT_SOURCE_SCOPE SS
    WHERE SS.DATA_SOURCE_ID=Q.DATA_SOURCE_ID
      AND SS.SCOPE_ID=Q.SCOPE_ID
      AND SS.ACTIVE='Y'
);

SELECT 'ESTADOS_OPERACIONALES_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_EMISSION_STATUS
WHERE (COMPLETENESS_PCT IS NOT NULL AND (COMPLETENESS_PCT < 0 OR COMPLETENESS_PCT > 100))
   OR EXPECTED_QTY < 0 OR EMITTED_QTY < 0 OR REJECTED_QTY < 0 OR ISSUE_QTY < 0;

SELECT 'LEGACY_CONTEXT_DOM_CYCLE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN ('RM_CFACT_DOM','RM_CFACT_CYCLE');

SELECT 'LEGACY_SIS_FACT_SIS_PREFIX' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'SIS_DATA_SOURCE','SIS_EXTRACTION_RUN','SIS_INTEGRATION_CALL',
 'SIS_AUDIT_LOG','SIS_AI_PROVIDER','SIS_USER'
);

SELECT 'SISGAV2_PROTEGIDA' CONTROL,
       CASE WHEN COUNT(*)=1 THEN 'EXISTE - FUERA DE BILLING ONE'
            ELSE 'NO EXISTE - SIN ACCION' END ESTADO
FROM USER_TABLES WHERE TABLE_NAME='SISGAV2';
