/* ============================================================
   BILLING ONE / SIS-FACT v0.2.0
   90_VALIDAR_BILLING_ONE.sql
   Certificación global greenfield - SOLO LECTURA.
   ============================================================ */

SELECT 'TABLAS_BILLING_ONE' CONTROL, COUNT(*) REAL, 23 ESPERADO,
       CASE WHEN COUNT(*)=23 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'RM_CFACT_ROLE','RM_CFACT_PERMISSION','RM_CFACT_ROLE_PERMISSION','RM_CFACT_USER',
 'RM_CFACT_USER_AUTH','RM_CFACT_USER_PERMISSION','RM_CFACT_LOGIN_RATE_LIMIT','RM_CFACT_AUDIT_LOG',
 'RM_CFACT_COMPANY','RM_CFACT_ISSUER','RM_CFACT_BUSINESS','RM_CFACT_DOM',
 'RM_CFACT_CYCLE','RM_CFACT_SCOPE','RM_CFACT_USER_SCOPE',
 'RM_CFACT_CONNECTION','RM_CFACT_CONNECTION_SCOPE','RM_CFACT_DATA_SOURCE',
 'RM_CFACT_DATA_SOURCE_PARAM','RM_CFACT_SOURCE_SCOPE','RM_CFACT_EXTRACTION_RUN',
 'RM_CFACT_INTEGRATION_CALL','RM_CFACT_CONNECTION_TEST'
);

SELECT 'OBJETOS_RM_CFACT_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND STATUS <> 'VALID';

SELECT 'INDICES_RM_CFACT_INVALIDOS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND STATUS <> 'VALID';

SELECT 'FK_RM_CFACT_NO_VALIDAS' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'RM_CFACT\_%' ESCAPE '\'
  AND CONSTRAINT_TYPE='R'
  AND (STATUS <> 'ENABLED' OR VALIDATED <> 'VALIDATED');

SELECT 'USUARIOS_SIN_AUTH' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER U
LEFT JOIN RM_CFACT_USER_AUTH A ON A.USER_ID=U.USER_ID
WHERE A.USER_ID IS NULL;

SELECT 'USUARIOS_ROL_INVALIDO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER U
LEFT JOIN RM_CFACT_ROLE R ON R.ROLE_ID=U.ROLE_ID
WHERE R.ROLE_ID IS NULL;

SELECT 'USUARIOS_OPERATIVOS_SIN_SCOPE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM (
    SELECT U.USER_ID
    FROM RM_CFACT_USER U
    JOIN RM_CFACT_ROLE R ON R.ROLE_ID=U.ROLE_ID
    LEFT JOIN RM_CFACT_USER_SCOPE US ON US.USER_ID=U.USER_ID
    WHERE U.ACTIVE='Y'
      AND R.ROLE_CODE IN ('OPERADOR','AUDITOR','VIEWER')
    GROUP BY U.USER_ID
    HAVING COUNT(US.SCOPE_ID)=0
);

SELECT 'USER_SCOPE_JERARQUIA_INVALIDA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_USER_SCOPE
WHERE (CAN_EXECUTE='Y' AND CAN_VIEW<>'Y')
   OR (CAN_CONFIGURE='Y' AND (CAN_EXECUTE<>'Y' OR CAN_VIEW<>'Y'));

SELECT 'SCOPES_ISSUER_OTRA_EMPRESA' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SCOPE S
JOIN RM_CFACT_ISSUER I ON I.ISSUER_ID=S.ISSUER_ID
WHERE S.COMPANY_ID <> I.COMPANY_ID;

SELECT 'FUENTES_SIN_CONEXION' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_CONNECTION C ON C.CONNECTION_ID=D.CONNECTION_ID
WHERE C.CONNECTION_ID IS NULL;

SELECT 'FUENTES_ACTIVAS_SIN_SCOPE' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_DATA_SOURCE D
LEFT JOIN RM_CFACT_SOURCE_SCOPE S ON S.DATA_SOURCE_ID=D.DATA_SOURCE_ID AND S.ACTIVE='Y'
WHERE D.ACTIVE='Y' AND S.SOURCE_SCOPE_ID IS NULL;

SELECT 'SOURCE_SCOPE_FUERA_CONN' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_SOURCE_SCOPE SS
JOIN RM_CFACT_DATA_SOURCE D ON D.DATA_SOURCE_ID=SS.DATA_SOURCE_ID
WHERE SS.ACTIVE='Y'
  AND EXISTS (
      SELECT 1 FROM RM_CFACT_CONNECTION_SCOPE CS0
      WHERE CS0.CONNECTION_ID=D.CONNECTION_ID AND CS0.ACTIVE='Y'
  )
  AND NOT EXISTS (
      SELECT 1 FROM RM_CFACT_CONNECTION_SCOPE CS
      WHERE CS.CONNECTION_ID=D.CONNECTION_ID
        AND CS.SCOPE_ID=SS.SCOPE_ID
        AND CS.ACTIVE='Y'
  );

SELECT 'CONFIG_CON_POSIBLE_SECRETO' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM RM_CFACT_CONNECTION
WHERE CONFIG_JSON IS NOT NULL
  AND (
       DBMS_LOB.INSTR(CONFIG_JSON, 'password') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'PASSWORD') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'secret') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'SECRET') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'token') > 0
    OR DBMS_LOB.INSTR(CONFIG_JSON, 'TOKEN') > 0
  );

SELECT 'LEGACY_SIS_FACT_SIS_PREFIX' CONTROL, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES
WHERE TABLE_NAME IN (
 'SIS_DATA_SOURCE','SIS_EXTRACTION_RUN','SIS_INTEGRATION_CALL',
 'SIS_AUDIT_LOG','SIS_AI_PROVIDER','SIS_USER'
);

SELECT 'SISGAV2_PROTEGIDA' CONTROL,
       CASE WHEN COUNT(*)=1 THEN 'EXISTE - FUERA DE BILLING ONE'
            ELSE 'NO EXISTE - SIN ACCION' END ESTADO
FROM USER_TABLES WHERE TABLE_NAME='SISGAV2';
