/* BILLING ONE v0.2.0 - 99_ROLLBACK_GREENFIELD.sql
   DESTRUCTIVO. Solo para una instalación greenfield/prueba de v0.2.0.
   NO usar como limpieza automática de la v0.1 productiva.
   SISGAV2 NO se referencia ni se toca. */

DECLARE
    PROCEDURE DROP_IF_EXISTS(P_TABLE VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ' || P_TABLE || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -942 THEN RAISE; END IF;
    END;
BEGIN
    DROP_IF_EXISTS('RM_CFACT_CONNECTION_TEST');
    DROP_IF_EXISTS('RM_CFACT_INTEGRATION_CALL');
    DROP_IF_EXISTS('RM_CFACT_EXTRACTION_RUN');
    DROP_IF_EXISTS('RM_CFACT_SOURCE_SCOPE');
    DROP_IF_EXISTS('RM_CFACT_DATA_SOURCE_PARAM');
    DROP_IF_EXISTS('RM_CFACT_DATA_SOURCE');
    DROP_IF_EXISTS('RM_CFACT_CONNECTION_SCOPE');
    DROP_IF_EXISTS('RM_CFACT_CONNECTION');

    DROP_IF_EXISTS('RM_CFACT_USER_SCOPE');
    DROP_IF_EXISTS('RM_CFACT_SCOPE');
    DROP_IF_EXISTS('RM_CFACT_CYCLE');
    DROP_IF_EXISTS('RM_CFACT_DOM');
    DROP_IF_EXISTS('RM_CFACT_BUSINESS');
    DROP_IF_EXISTS('RM_CFACT_ISSUER');
    DROP_IF_EXISTS('RM_CFACT_COMPANY');

    DROP_IF_EXISTS('RM_CFACT_AUDIT_LOG');
    DROP_IF_EXISTS('RM_CFACT_LOGIN_RATE_LIMIT');
    DROP_IF_EXISTS('RM_CFACT_USER_PERMISSION');
    DROP_IF_EXISTS('RM_CFACT_USER_AUTH');
    DROP_IF_EXISTS('RM_CFACT_USER');
    DROP_IF_EXISTS('RM_CFACT_ROLE_PERMISSION');
    DROP_IF_EXISTS('RM_CFACT_PERMISSION');
    DROP_IF_EXISTS('RM_CFACT_ROLE');
END;
/
