/* ============================================================
   BILLING ONE / SIS-FACT v0.2.1
   99_ROLLBACK_GREENFIELD.sql
   DESTRUCTIVO - SOLO PARA INSTALACION GREENFIELD DE BILLING ONE.

   NUNCA usar como migración v0.1/v0.2 ni con datos productivos.
   SISGAV2 NO SE TOCA.
   ============================================================ */

DROP TABLE RM_CFACT_ISSUE CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_EMISSION_STATUS CASCADE CONSTRAINTS PURGE;

DROP TABLE RM_CFACT_CONNECTION_TEST CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_INTEGRATION_CALL CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_EXTRACTION_RUN CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_SOURCE_SCOPE CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_DATA_SOURCE_PARAM CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_DATA_SOURCE CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_CONNECTION_SCOPE CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_CONNECTION CASCADE CONSTRAINTS PURGE;

DROP TABLE RM_CFACT_USER_SCOPE CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_SCOPE CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_FLOW CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_EMISSION_TYPE CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_ORIGIN CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_ISSUER CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_BUSINESS CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_COMPANY CASCADE CONSTRAINTS PURGE;

DROP TABLE RM_CFACT_AUDIT_LOG CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_LOGIN_RATE_LIMIT CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_USER_PERMISSION CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_USER_AUTH CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_USER CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_ROLE_PERMISSION CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_PERMISSION CASCADE CONSTRAINTS PURGE;
DROP TABLE RM_CFACT_ROLE CASCADE CONSTRAINTS PURGE;
